package graphique;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import gestionnaires.*;

/**
 *
 * @author Coyotito
 */
public class FrameArticles extends javax.swing.JFrame implements ActionListener {
	
	                    
    private javax.swing.JMenu affichage;
    private javax.swing.JInternalFrame articlesFrame;
    private javax.swing.JMenuBar articlesMenu;
    private javax.swing.JPanel choixPanel;
    private javax.swing.JMenu creation;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu suppression;
    
    
    private GestionTableDesArticles GTA;
    //private TableDes
    /**
     * Creates new form FrameArticles
     */
    public FrameArticles(GestionTableDesArticles GTA) {
        this.GTA = GTA;
    	initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        articlesFrame = new javax.swing.JInternalFrame();
        choixPanel = new javax.swing.JPanel();
        articlesMenu = new javax.swing.JMenuBar();
        affichage = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        creation = new javax.swing.JMenu();
        suppression = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        articlesFrame.setBackground(new java.awt.Color(204, 204, 255));
        articlesFrame.setVisible(true);

        choixPanel.setBackground(new java.awt.Color(153, 204, 255));
        choixPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "choix", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri Light", 1, 10), new java.awt.Color(0, 0, 0))); // NOI18N
        choixPanel.setFont(new java.awt.Font("Calibri Light", 1, 11)); // NOI18N

        javax.swing.GroupLayout choixPanelLayout = new javax.swing.GroupLayout(choixPanel);
        choixPanel.setLayout(choixPanelLayout);
        choixPanelLayout.setHorizontalGroup(
            choixPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );
        choixPanelLayout.setVerticalGroup(
            choixPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 205, Short.MAX_VALUE)
        );

        affichage.setText("affichage");

        jMenu1.setText("tous les articles");
        affichage.add(jMenu1);

        jMenu2.setText("articles en promotion");
        affichage.add(jMenu2);

        articlesMenu.add(affichage);

        creation.setText("création");
        articlesMenu.add(creation);

        suppression.setText("suppression");
        articlesMenu.add(suppression);

        articlesFrame.setJMenuBar(articlesMenu);

        javax.swing.GroupLayout articlesFrameLayout = new javax.swing.GroupLayout(articlesFrame.getContentPane());
        articlesFrame.getContentPane().setLayout(articlesFrameLayout);
        articlesFrameLayout.setHorizontalGroup(
            articlesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(choixPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        articlesFrameLayout.setVerticalGroup(
            articlesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(choixPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(articlesFrame)
                    .addGap(31, 31, 31)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(articlesFrame)
                    .addGap(14, 14, 14)))
        );

        pack();
    }// </editor-fold>                        

   
   

	@Override
	public void actionPerformed(ActionEvent e) {
		/*
		 * String lib = e.getActionCommand();
		 
		if (lib.equals("tous les articlese")) {GTA. }
		else if(lib.equals("Affichage Formulaire")) {
		GestionTabArticles.affichageFormulaireTabArt(tabArt,true,true);
		// ==> true + true cas 1 er appel pou remettre à 0 l'indice
		}
		else if(lib.equals("Affichage Articles Promo")) { GestionTabArticles.affichageListArtPromo(tabArt); }
		else if(lib.equals("Création/Ajout")) { GestionTabArticles.creationArticle(tabArt); }
		else if(lib.equals("Suppression")) { GestionTabArticles.suppArticle(tabArt; }
		else if(lib.equals("Modification")) { GestionTabArticles.miseAJourArticle(tabArt); }
		else if(lib.equals("Retour")) {this.hide(); new ClientSerie62(); }
		else if(lib.equals("Sauvegarde")) {GestionTabArticles.sauvegarde(tabArt,nomPhysiqueArticles); }
		}
		*/
	}

       
}
                      


