package graphique;

import java.awt.MenuBar;

import javax.swing.*;


import gestionnaires.GestionGenerale;
//import gestionnaires.GestionTableDesArticles;
//import gestionnaires.GestionTableDesCommandes;
//import gestionnaires.GestionTableFacture;
import iPane.ES;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *Création de la fenetre principale du programme, avec les trois bouton sur la gauche 
 *qui font appelle au différent gestionnaires
 * @author Morane Gruenpeter
 */

public class GraphiqueFrame extends javax.swing.JFrame {
	 // Variables declaration                    
    private javax.swing.JButton SortiBouton;
    private javax.swing.JButton articlesBouton;
    private javax.swing.JButton commandesBouton;
    private javax.swing.JButton facturesBouton;
    
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton saveBouton;
    

    private GestionGenerale GG;

    /**
     * Creates new form GraphiqueFrame
     */
    public GraphiqueFrame(GestionGenerale GG) {
        initComponents();
        this.GG = GG;
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        //les bouton
        articlesBouton = new javax.swing.JButton();
        commandesBouton = new javax.swing.JButton();
        facturesBouton = new javax.swing.JButton();
        SortiBouton = new javax.swing.JButton();
        saveBouton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 102));

        jInternalFrame1.setBackground(new java.awt.Color(255, 204, 204));
        jInternalFrame1.setVisible(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jTextArea1.setBackground(new java.awt.Color(204, 204, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("    \tBienvenue à la superette!\n\n     Projet système d'information\n\t\n\t   NFA019 CNAM Paris\n\t\n\n\t\n\n\n\n\n\t    Morane Gruenpeter\n");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        
        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
	
        articlesBouton.setBackground(new java.awt.Color(204, 255, 204));
        articlesBouton.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        articlesBouton.setText("Articles");
        articlesBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                articlesBoutonActionPerformed(evt);
            }
        });

        commandesBouton.setBackground(new java.awt.Color(204, 255, 204));
        commandesBouton.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        commandesBouton.setText("Commandes");
        commandesBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commandesBoutonActionPerformed(evt);
            }
        });

        facturesBouton.setBackground(new java.awt.Color(204, 255, 204));
        facturesBouton.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        facturesBouton.setText("Factures");
        facturesBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturesBoutonActionPerformed(evt);
            }
        });

        SortiBouton.setBackground(new java.awt.Color(204, 255, 204));
        SortiBouton.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        SortiBouton.setText("sortie");
        SortiBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortiBoutonActionPerformed(evt);
            }
        });

        saveBouton.setBackground(new java.awt.Color(204, 255, 204));
        saveBouton.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        saveBouton.setText("save");
        saveBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBoutonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(articlesBouton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(commandesBouton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SortiBouton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveBouton))
                    .addComponent(facturesBouton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jInternalFrame1)
                )
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addComponent(jInternalFrame1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(articlesBouton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(commandesBouton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(facturesBouton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SortiBouton, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(saveBouton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>                        

    private void facturesBoutonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        GG.appelGestionFactures();
    }                                              

    private void commandesBoutonActionPerformed(java.awt.event.ActionEvent evt) {                                                
    	GG.appelGestionCommandes();
    }                                               

    private void saveBoutonActionPerformed(java.awt.event.ActionEvent evt) {                                           
    	GG.ecrire();
    	
    }                                          

    private void SortiBoutonActionPerformed(java.awt.event.ActionEvent evt) {                                            
    	//ajouter fenetre de demande de sauvegarde!!!!!!!!!!!!
    	ES.affiche("La superrette","AU REVOIR...  ET A BIENTOT SUR SUPERETTE");
    	
    	//ferme la fenetre et arrete le programme
    	this.dispose();
    }                                           

    private void articlesBoutonActionPerformed(java.awt.event.ActionEvent evt) {                                               
    	
    	GG.appelGestionArticles();
    	//CustomMenuBar CMB = new CustomMenuBar("affichage", "creation", "supression", "tous les articles","articles en promotion");
    	//jInternalFrame1.add(CMB);

         
    
    }                                              

    

                
}
